name: Build and Deploy Spring Boot Service User Service

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy User Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Unit Tests
        run: mvn -B test --file pom.xml  # -B = --batch-mode

      - name: Build the application
        run: |
          mvn clean install
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/user-service:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-actions@v3
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/user-service:latest